### PR TITLE
Create Tinkers+Foundry.zs

### PR DESCRIPTION
**Pull request by bookerthegeek**
Fixes the recipes for tinkers constructs casts in the foundry metal caster.

### CODE REVIEW

**Comment by johnfg12** [comment]
weapons are still disabled correct?

**Comment by bookerthegeek** [comment]
Nope, do they need to be? This is all patterns. Would you like the weapons removed?

**Comment by johnfg12** [comment]
if u could :)

**Comment by bookerthegeek** [comment]
Removed or commented out?

**Comment by Sandstroem** [comment]
Doesnt really matter I think. Chisel was also removed.

Here is an older discussion where Caithleen stated this: https://github.com/MyM-ModpackTeam/hypovolemia/issues/42

**Comment by bookerthegeek** [comment]
I'll remove the weapons, but their are decorative blocks only craftable with the tinkers chisel.

**Comment by Sandstroem** [comment]
Hm ok, I guess then leave it in. Doesn't really matter.
What decorative blocks? Maybe someone put in the wrong chisel.

**Comment by bookerthegeek** [comment]
Fixed. Included are:
- Tools
- Nuggets
- Ingots
- Gem Cast
- Gear Cast
- Chisel

**Comment by johnfg12** [comment]
so this is compete or in progress?

**Comment by bookerthegeek** [comment]
Fixed https://github.com/MyM-ModpackTeam/hypovolemia/issues/214

**Pull request merged**
