### PR TITLE
Update Misc.zs

### PR DESCRIPTION
**Pull request by bookerthegeek**
Fixes https://github.com/MyM-ModpackTeam/hypovolemia/issues/238

Going to leave it open for a day. Maybe somebody knows how to fix the Lexicon?

### CODE REVIEW

**Comment by johnfg12** [comment]
@kindlich can we fix the lexicon?

**Comment by bookerthegeek** [comment]
Technically it is fixable. I don't know how to do so.

**Comment by johnfg12** [comment]
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Botania_Support:Lexica_Botania
what needs doing in it?

**Comment by bookerthegeek** [comment]
I need the page numbers for the research pages. It is not working for me.

**Comment by kindlich** [comment]
Ok, you'll need to remove the 2nd page from the lexicon entry and then just re-add it xD

use this to remove the 2nd lexicon page (since the pages are an array it starts with 0)
`mods.botania.Lexicon.removePage("tc.research_name.TECHNOBASICS", 1);`

and this to add the alchemy recipe for the Mana Coil on the 2nd page...
`mods.botania.Lexicon.addAlchemyPage("techno:itemBO.0.name", "tc.research_name.TECHNOBASICS", 1, [<technom:itemBO>], [<Botania:manaResource:23>],[1000]);`

http://puu.sh/pRd6c/9ebc0aa220.jpg <-- looks like that

should work like that but better test 1st xD

**Comment by johnfg12** [comment]
image
seems to work

**Pull request merged**
