### PR TITLE
Last worldgen fixes

### PR DESCRIPTION
**Pull request by Bennyboy1695**

### CODE REVIEW

**Comment by Sir-Will** [comment]
Still no structures and the bones in the ground have the wrong texture

**Comment by Sir-Will** [comment]
Also, the grass generates under water because there are the same blocks as overground.

**Comment by Bennyboy1695** [comment]
I was able to get structures and everything in my multiple test worlds.
The ocean thing i have no idea how to fix, i can't get biometweaker to set different blocks under the water/blood no matter what setting i use

**Comment by Sir-Will** [comment]
Compare my worldgen commits with the current files.

**Comment by Bennyboy1695** [comment]
I did, the only differences is the blocks used from what I can see.

**Comment by johnfg12** [comment]
would it not be easier to put this gen in hypo extra that way u should be able to stop the under water spawning issue

**Comment by Sir-Will** [comment]
https://github.com/MyM-ModpackTeam/hypovolemia/blob/4a8076aad698fe68cc3b8176d53be304b6fc9581/src/config/BiomeTweaker/Overworld.cfg#L13-L23
You have to use a block where you can't place grass on

**Comment by Bennyboy1695** [comment]
Everything should be fixed now

**Comment by Slind14** [comment]
did you even test the worlgen changes?
https://i.imgur.com/NTlBKn6.png

**Pull request merged**
